============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.26.4
collecting ... collected 7 items

test_agentsPUT_endpoints.tavern.yaml::PUT /agents/group/{group_id} PASSED [ 14%]
test_agentsPUT_endpoints.tavern.yaml::PUT /agents/groups/{group_id}/configuration PASSED [ 28%]
test_agentsPUT_endpoints.tavern.yaml::PUT /agents/restart FAILED         [ 42%]
test_agentsPUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED [ 57%]
test_agentsPUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED [ 71%]
test_agentsPUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade SKIPPED [ 85%]
test_agentsPUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom SKIPPED [100%]

=================================== FAILURES ===================================
_ /home/davidjiglesias/git/wazuh/api/test/integration/test_agentsPUT_endpoints.tavern.yaml::PUT /agents/restart _
Format variables:
  protocol:s = 'http'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImlhdCI6MTU3MTkzNTA5NywiZXhwIjoxNTcxOTcxMDk3LCJzdWIiOiJ3YXp1aCIsInJiYWNfcG9saWNpZXMiOnt9fQ.FityrJCkOE_I0KnvyP3vnKXui1AXM_9V6UNHPYBVuHw'

Source test stage (line 366):
  - name: Try to restart all agents
    request:
      url: "{protocol:s}://{host:s}:{port:d}/agents/restart"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      status_code: 200
      body:
        data:
          affected_items: !anything
          failed_items: !anything
          total_affected_items: 7
          total_failed_items: 5
        message: !anystr
    delay_after: 40


Formatted stage:
  delay_after: 40
  name: Try to restart all agents
  request:
    headers:
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImlhdCI6MTU3MTkzNTA5NywiZXhwIjoxNTcxOTcxMDk3LCJzdWIiOiJ3YXp1aCIsInJiYWNfcG9saWNpZXMiOnt9fQ.FityrJCkOE_I0KnvyP3vnKXui1AXM_9V6UNHPYBVuHw
    method: PUT
    url: 'http://localhost:55000/agents/restart'
  response:
    body:
      data:
        affected_items: !anything ''
        failed_items: !anything ''
        total_affected_items: 7
        total_failed_items: 5
      message: !anystr ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Try to restart all agents' failed:
    - Value mismatch in body: Key mismatch: (expected["data"]["total_failed_items"] = '5' (type = <class 'int'>), actual["data"]["total_failed_items"] = '3' (type = <class 'int'>))
------------------------------ Captured log call -------------------------------
dict_util.py               314 WARNING  Structure of returned data was different than expected  - Extra keys in response: {'message', 'remediation'} (expected["data"]["failed_items"]["0"]["error"] = '{'code': 1701}' (type = <class 'dict'>), actual["data"]["failed_items"]["0"]["error"] = '{'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}' (type = <class 'dict'>))
Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af...to any agent'} == {'data': {'aff...7f21c61a6a20>}
  Differing items:
  {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1701, 'message': 'Agent does not exist', 'remediat...t=id,name` to find all available agents'}, 'id': ['998', '999']}], 'total_affected_items': 0, 'total_failed_items': 2}} != {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1701}, 'id': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}], 'total_affected_items': 0, 'total_failed_items': 2}}
  {'message': 'Could not send command to any agent'} != {'message': <tavern.util.loader.StrSentinel object at 0x7f21c61a6a20>}
  Full diff:
  {'data': {'affected_items': [],
  -           'failed_items': [{'error': {'code': 1701,
  +           'failed_items': [{'error': {'code': 1701},
  ?                                                   +
  +                             'id': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}],
  -                                       'message': 'Agent does not exist',
  -                                       'remediation': 'Please, use `GET '
  -                                                      '/agents?select=id,name` '
  -                                                      'to find all available '
  -                                                      'agents'},
  -                             'id': ['998', '999']}],
  'total_affected_items': 0,
  'total_failed_items': 2},
  -  'message': 'Could not send command to any agent'}
  +  'message': <tavern.util.loader.StrSentinel object at 0x7f21c61a6a20>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 2} == {'affected_ite...led_items': 2}
  Common items:
  {'affected_items': [], 'total_affected_items': 0, 'total_failed_items': 2}
  Differing items:
  {'failed_items': [{'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}, 'id': ['998', '999']}]} != {'failed_items': [{'error': {'code': 1701}, 'id': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}]}
  Full diff:
  {'affected_items': [],
  -  'failed_items': [{'error': {'code': 1701,
  +  'failed_items': [{'error': {'code': 1701},
  ?                                          +
  +                    'id': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}],
  -                              'message': 'Agent does not exist',
  -                              'remediation': 'Please, use `GET '
  -                                             '/agents?select=id,name` to find '
  -                                             'all available agents'},
  -                    'id': ['998', '999']}],
  'total_affected_items': 0,
  'total_failed_items': 2}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [{'error': {'...998', '999']}] == [{'error': {'c...f21c627ab38>}]
  At index 0 diff: {'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}, 'id': ['998', '999']} != {'error': {'code': 1701}, 'id': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}
  Full diff:
  - [{'error': {'code': 1701,
  + [{'error': {'code': 1701},
  ?                         +
  +   'id': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}]
  -             'message': 'Agent does not exist',
  -             'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                            'all available agents'},
  -   'id': ['998', '999']}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'error': {'c...'998', '999']} == {'error': {'co...7f21c627ab38>}
  Differing items:
  {'id': ['998', '999']} != {'id': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}
  {'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}} != {'error': {'code': 1701}}
  Full diff:
  - {'error': {'code': 1701,
  + {'error': {'code': 1701},
  ?                        +
  +  'id': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}
  -            'message': 'Agent does not exist',
  -            'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                           'all available agents'},
  -  'id': ['998', '999']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'code': 1701...lable agents'} == {'code': 1701}
  Common items:
  {'code': 1701}
  Left contains more items:
  {'message': 'Agent does not exist',
   'remediation': 'Please, use `GET /agents?select=id,name` to find all '
                  'available agents'}
  Full diff:
  - {'code': 1701,
  ?              ^
  + {'code': 1701}
  ?              ^
  -  'message': 'Agent does not exist',
  -  'remediation': 'Please, use `GET /agents?select=id,name` to find all '
  -                 'available agents'}
dict_util.py               314 WARNING  Structure of returned data was different than expected  - Extra keys in response: {'message', 'remediation'} (expected["data"]["failed_items"]["0"]["error"] = '{'code': 1701}' (type = <class 'dict'>), actual["data"]["failed_items"]["0"]["error"] = '{'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}' (type = <class 'dict'>))
Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af...to any agent'} == {'data': {'aff...7f21c61b7b38>}
  Differing items:
  {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1701, 'message': 'Agent does not exist', 'remediat...d make sure you select an agent other than 000'}, 'id': ['000']}], 'total_affected_items': 0, 'total_failed_items': 2}} != {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1701}, 'id': ['999']}, {'error': {'code': 1703}, 'id': ['000']}], 'total_affected_items': 0, 'total_failed_items': 2}}
  {'message': 'Could not send command to any agent'} != {'message': <tavern.util.loader.StrSentinel object at 0x7f21c61b7b38>}
  Full diff:
  {'data': {'affected_items': [],
  -           'failed_items': [{'error': {'code': 1701,
  +           'failed_items': [{'error': {'code': 1701}, 'id': ['999']},
  ?                                                   + ++++++++++++++++
  -                                       'message': 'Agent does not exist',
  -                                       'remediation': 'Please, use `GET '
  -                                                      '/agents?select=id,name` '
  -                                                      'to find all available '
  -                                                      'agents'},
  -                             'id': ['999']},
  -                            {'error': {'code': 1703,
  +                            {'error': {'code': 1703}, 'id': ['000']}],
  ?                                                   + +++++++++++++++++
  -                                       'message': 'Action not available for '
  -                                                  'Manager (Agent 000)',
  -                                       'remediation': 'Please, use `GET '
  -                                                      '/agents?select=id,name` '
  -                                                      'to find all available '
  -                                                      'agents and make sure you '
  -                                                      'select an agent other '
  -                                                      'than 000'},
  -                             'id': ['000']}],
  'total_affected_items': 0,
  'total_failed_items': 2},
  -  'message': 'Could not send command to any agent'}
  +  'message': <tavern.util.loader.StrSentinel object at 0x7f21c61b7b38>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 2} == {'affected_ite...led_items': 2}
  Common items:
  {'affected_items': [], 'total_affected_items': 0, 'total_failed_items': 2}
  Differing items:
  {'failed_items': [{'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents...gents?select=id,name` to find all available agents and make sure you select an agent other than 000'}, 'id': ['000']}]} != {'failed_items': [{'error': {'code': 1701}, 'id': ['999']}, {'error': {'code': 1703}, 'id': ['000']}]}
  Full diff:
  {'affected_items': [],
  -  'failed_items': [{'error': {'code': 1701,
  +  'failed_items': [{'error': {'code': 1701}, 'id': ['999']},
  ?                                          + ++++++++++++++++
  -                              'message': 'Agent does not exist',
  -                              'remediation': 'Please, use `GET '
  -                                             '/agents?select=id,name` to find '
  -                                             'all available agents'},
  -                    'id': ['999']},
  -                   {'error': {'code': 1703,
  +                   {'error': {'code': 1703}, 'id': ['000']}],
  ?                                          + +++++++++++++++++
  -                              'message': 'Action not available for Manager '
  -                                         '(Agent 000)',
  -                              'remediation': 'Please, use `GET '
  -                                             '/agents?select=id,name` to find '
  -                                             'all available agents and make '
  -                                             'sure you select an agent other '
  -                                             'than 000'},
  -                    'id': ['000']}],
  'total_affected_items': 0,
  'total_failed_items': 2}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [{'error': {'...id': ['000']}] == [{'error': {'c...id': ['000']}]
  At index 0 diff: {'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}, 'id': ['999']} != {'error': {'code': 1701}, 'id': ['999']}
  Full diff:
  + [{'error': {'code': 1701}, 'id': ['999']},
  +  {'error': {'code': 1703}, 'id': ['000']}]
  - [{'error': {'code': 1701,
  -             'message': 'Agent does not exist',
  -             'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                            'all available agents'},
  -   'id': ['999']},
  -  {'error': {'code': 1703,
  -             'message': 'Action not available for Manager (Agent 000)',
  -             'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                            'all available agents and make sure you select an '
  -                            'agent other than 000'},
  -   'id': ['000']}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'error': {'c...'id': ['999']} == {'error': {'co...'id': ['999']}
  Common items:
  {'id': ['999']}
  Differing items:
  {'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}} != {'error': {'code': 1701}}
  Full diff:
  - {'error': {'code': 1701,
  + {'error': {'code': 1701}, 'id': ['999']}
  ?                        + +++++++++++++++
  -            'message': 'Agent does not exist',
  -            'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                           'all available agents'},
  -  'id': ['999']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'code': 1701...lable agents'} == {'code': 1701}
  Common items:
  {'code': 1701}
  Left contains more items:
  {'message': 'Agent does not exist',
   'remediation': 'Please, use `GET /agents?select=id,name` to find all '
                  'available agents'}
  Full diff:
  - {'code': 1701,
  ?              ^
  + {'code': 1701}
  ?              ^
  -  'message': 'Agent does not exist',
  -  'remediation': 'Please, use `GET /agents?select=id,name` to find all '
  -                 'available agents'}
dict_util.py               314 WARNING  Structure of returned data was different than expected  - Extra keys in response: {'message', 'remediation'} (expected["data"]["failed_items"]["1"]["error"] = '{'code': 1703}' (type = <class 'dict'>), actual["data"]["failed_items"]["1"]["error"] = '{'code': 1703, 'message': 'Action not available for Manager (Agent 000)', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents and make sure you select an agent other than 000'}' (type = <class 'dict'>))
Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af...to any agent'} == {'data': {'aff...7f21c61b7b38>}
  Differing items:
  {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1701, 'message': 'Agent does not exist', 'remediat...d make sure you select an agent other than 000'}, 'id': ['000']}], 'total_affected_items': 0, 'total_failed_items': 2}} != {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1701}, 'id': ['999']}, {'error': {'code': 1703}, 'id': ['000']}], 'total_affected_items': 0, 'total_failed_items': 2}}
  {'message': 'Could not send command to any agent'} != {'message': <tavern.util.loader.StrSentinel object at 0x7f21c61b7b38>}
  Full diff:
  {'data': {'affected_items': [],
  -           'failed_items': [{'error': {'code': 1701,
  +           'failed_items': [{'error': {'code': 1701}, 'id': ['999']},
  ?                                                   + ++++++++++++++++
  -                                       'message': 'Agent does not exist',
  -                                       'remediation': 'Please, use `GET '
  -                                                      '/agents?select=id,name` '
  -                                                      'to find all available '
  -                                                      'agents'},
  -                             'id': ['999']},
  -                            {'error': {'code': 1703,
  +                            {'error': {'code': 1703}, 'id': ['000']}],
  ?                                                   + +++++++++++++++++
  -                                       'message': 'Action not available for '
  -                                                  'Manager (Agent 000)',
  -                                       'remediation': 'Please, use `GET '
  -                                                      '/agents?select=id,name` '
  -                                                      'to find all available '
  -                                                      'agents and make sure you '
  -                                                      'select an agent other '
  -                                                      'than 000'},
  -                             'id': ['000']}],
  'total_affected_items': 0,
  'total_failed_items': 2},
  -  'message': 'Could not send command to any agent'}
  +  'message': <tavern.util.loader.StrSentinel object at 0x7f21c61b7b38>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 2} == {'affected_ite...led_items': 2}
  Common items:
  {'affected_items': [], 'total_affected_items': 0, 'total_failed_items': 2}
  Differing items:
  {'failed_items': [{'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents...gents?select=id,name` to find all available agents and make sure you select an agent other than 000'}, 'id': ['000']}]} != {'failed_items': [{'error': {'code': 1701}, 'id': ['999']}, {'error': {'code': 1703}, 'id': ['000']}]}
  Full diff:
  {'affected_items': [],
  -  'failed_items': [{'error': {'code': 1701,
  +  'failed_items': [{'error': {'code': 1701}, 'id': ['999']},
  ?                                          + ++++++++++++++++
  -                              'message': 'Agent does not exist',
  -                              'remediation': 'Please, use `GET '
  -                                             '/agents?select=id,name` to find '
  -                                             'all available agents'},
  -                    'id': ['999']},
  -                   {'error': {'code': 1703,
  +                   {'error': {'code': 1703}, 'id': ['000']}],
  ?                                          + +++++++++++++++++
  -                              'message': 'Action not available for Manager '
  -                                         '(Agent 000)',
  -                              'remediation': 'Please, use `GET '
  -                                             '/agents?select=id,name` to find '
  -                                             'all available agents and make '
  -                                             'sure you select an agent other '
  -                                             'than 000'},
  -                    'id': ['000']}],
  'total_affected_items': 0,
  'total_failed_items': 2}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [{'error': {'...id': ['000']}] == [{'error': {'c...id': ['000']}]
  At index 0 diff: {'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}, 'id': ['999']} != {'error': {'code': 1701}, 'id': ['999']}
  Full diff:
  + [{'error': {'code': 1701}, 'id': ['999']},
  +  {'error': {'code': 1703}, 'id': ['000']}]
  - [{'error': {'code': 1701,
  -             'message': 'Agent does not exist',
  -             'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                            'all available agents'},
  -   'id': ['999']},
  -  {'error': {'code': 1703,
  -             'message': 'Action not available for Manager (Agent 000)',
  -             'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                            'all available agents and make sure you select an '
  -                            'agent other than 000'},
  -   'id': ['000']}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'error': {'c...'id': ['000']} == {'error': {'co...'id': ['000']}
  Common items:
  {'id': ['000']}
  Differing items:
  {'error': {'code': 1703, 'message': 'Action not available for Manager (Agent 000)', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents and make sure you select an agent other than 000'}} != {'error': {'code': 1703}}
  Full diff:
  - {'error': {'code': 1703,
  + {'error': {'code': 1703}, 'id': ['000']}
  ?                        + +++++++++++++++
  -            'message': 'Action not available for Manager (Agent 000)',
  -            'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                           'all available agents and make sure you select an '
  -                           'agent other than 000'},
  -  'id': ['000']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'code': 1703...her than 000'} == {'code': 1703}
  Common items:
  {'code': 1703}
  Left contains more items:
  {'message': 'Action not available for Manager (Agent 000)',
   'remediation': 'Please, use `GET /agents?select=id,name` to find all '
                  'available agents and make sure you select an agent other than '
                  '000'}
  Full diff:
  - {'code': 1703,
  ?              ^
  + {'code': 1703}
  ?              ^
  -  'message': 'Action not available for Manager (Agent 000)',
  -  'remediation': 'Please, use `GET /agents?select=id,name` to find all '
  -                 'available agents and make sure you select an agent other than '
  -                 '000'}
dict_util.py               314 WARNING  Structure of returned data was different than expected  - Extra keys in response: {'message', 'remediation'} (expected["data"]["failed_items"]["0"]["error"] = '{'code': 1701}' (type = <class 'dict'>), actual["data"]["failed_items"]["0"]["error"] = '{'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}' (type = <class 'dict'>))
Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af... some agents'} == {'data': {'aff...7f21c61be9b0>}
  Differing items:
  {'data': {'affected_items': ['002', '001'], 'failed_items': [{'error': {'code': 1701, 'message': 'Agent does not exist...s?select=id,name` to find all available agents'}, 'id': ['999']}], 'total_affected_items': 2, 'total_failed_items': 1}} != {'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>, 'failed_items': [{'error': {'code': 1701}, 'id': ['999']}], 'total_affected_items': 2, 'total_failed_items': 1}}
  {'message': 'Could not send command to some agents'} != {'message': <tavern.util.loader.StrSentinel object at 0x7f21c61be9b0>}
  Full diff:
  - {'data': {'affected_items': ['002', '001'],
  + {'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>,
  -           'failed_items': [{'error': {'code': 1701,
  +           'failed_items': [{'error': {'code': 1701}, 'id': ['999']}],
  ?                                                   + +++++++++++++++++
  -                                       'message': 'Agent does not exist',
  -                                       'remediation': 'Please, use `GET '
  -                                                      '/agents?select=id,name` '
  -                                                      'to find all available '
  -                                                      'agents'},
  -                             'id': ['999']}],
  'total_affected_items': 2,
  'total_failed_items': 1},
  -  'message': 'Could not send command to some agents'}
  +  'message': <tavern.util.loader.StrSentinel object at 0x7f21c61be9b0>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 1} == {'affected_ite...led_items': 1}
  Common items:
  {'total_affected_items': 2, 'total_failed_items': 1}
  Differing items:
  {'affected_items': ['002', '001']} != {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>}
  {'failed_items': [{'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}, 'id': ['999']}]} != {'failed_items': [{'error': {'code': 1701}, 'id': ['999']}]}
  Full diff:
  - {'affected_items': ['002', '001'],
  + {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f21c627ab38>,
  -  'failed_items': [{'error': {'code': 1701,
  +  'failed_items': [{'error': {'code': 1701}, 'id': ['999']}],
  ?                                          + +++++++++++++++++
  -                              'message': 'Agent does not exist',
  -                              'remediation': 'Please, use `GET '
  -                                             '/agents?select=id,name` to find '
  -                                             'all available agents'},
  -                    'id': ['999']}],
  'total_affected_items': 2,
  'total_failed_items': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [{'error': {'...id': ['999']}] == [{'error': {'c...id': ['999']}]
  At index 0 diff: {'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}, 'id': ['999']} != {'error': {'code': 1701}, 'id': ['999']}
  Full diff:
  + [{'error': {'code': 1701}, 'id': ['999']}]
  - [{'error': {'code': 1701,
  -             'message': 'Agent does not exist',
  -             'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                            'all available agents'},
  -   'id': ['999']}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'error': {'c...'id': ['999']} == {'error': {'co...'id': ['999']}
  Common items:
  {'id': ['999']}
  Differing items:
  {'error': {'code': 1701, 'message': 'Agent does not exist', 'remediation': 'Please, use `GET /agents?select=id,name` to find all available agents'}} != {'error': {'code': 1701}}
  Full diff:
  - {'error': {'code': 1701,
  + {'error': {'code': 1701}, 'id': ['999']}
  ?                        + +++++++++++++++
  -            'message': 'Agent does not exist',
  -            'remediation': 'Please, use `GET /agents?select=id,name` to find '
  -                           'all available agents'},
  -  'id': ['999']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 270, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'code': 1701...lable agents'} == {'code': 1701}
  Common items:
  {'code': 1701}
  Left contains more items:
  {'message': 'Agent does not exist',
   'remediation': 'Please, use `GET /agents?select=id,name` to find all '
                  'available agents'}
  Full diff:
  - {'code': 1701,
  ?              ^
  + {'code': 1701}
  ?              ^
  -  'message': 'Agent does not exist',
  -  'remediation': 'Please, use `GET /agents?select=id,name` to find all '
  -                 'available agents'}
base.py                     41 ERROR    Value mismatch in body: Key mismatch: (expected["data"]["total_failed_items"] = '5' (type = <class 'int'>), actual["data"]["total_failed_items"] = '3' (type = <class 'int'>))
=============================== warnings summary ===============================
test/integration/test_agentsPUT_endpoints.tavern.yaml::PUT /agents/group/{group_id}
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========== 1 failed, 4 passed, 2 skipped, 1 warnings in 40.96 seconds ==========
